### ISSUE TITLE
Debian buid fail

### ISSUE THREAD

**Issue by fabrixx** [mozilla/tofino#91] opened 2016-04-12 18:14 UTC
Hi
When i try i Debian building i receive:
root@debian:/home/fabrizio/Scrivania# npm install tofino
npm WARN engine tofino@0.1.0: wanted: {"node":">=5.8.0"} (current: {"node":"4.3.1","npm":"1.4.21"})
npm WARN optional dep failed, continuing fsevents@1.0.11
|
> tofino@0.1.0 postinstall /home/fabrizio/Scrivania/node_modules/tofino
> electron-rebuild

sh: 1: electron-rebuild: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! tofino@0.1.0 postinstall: `electron-rebuild`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the tofino@0.1.0 postinstall script.
npm ERR! This is most likely a problem with the tofino package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! electron-rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls tofino
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "tofino"
npm ERR! cwd /home/fabrizio/Scrivania
npm ERR! node -v v4.3.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR! /home/fabrizio/Scrivania/npm-debug.log
npm ERR! not ok code 0
root@debian:/home/fabrizio/Scrivania#

**Comment by linclark** [comment] 2016-04-12 18:22
This might be because of the version of Node.js that you're using. It looks like you're on 4.3.1 but the `package.json` specifies `>=5.8.0`. Also, you'll want to update your version of npm.

**Comment by fabrixx** [comment] 2016-04-12 20:19
Upgraded node and npm  to 5.8.0 but now i have:

> root@debian:/home/fabrizio/Scrivania# npm install tofino
>
> > tofino@0.1.0 postinstall /home/fabrizio/Scrivania/node_modules/tofino
> > electron-rebuild
>
> sh: 1: electron-rebuild: not found
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture:
> fsevents@1.0.11
> npm WARN enoent ENOENT: no such file or directory, open
> '/home/fabrizio/Scrivania/package.json'
> npm WARN Scrivania No description
> npm WARN Scrivania No repository field.
> npm WARN Scrivania No README data
> npm WARN Scrivania No license field.
> npm WARN You are using a pre-release version of node and things may not
> work as expected
> npm ERR! Linux 4.4.0-1-amd64
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "tofino"
> npm ERR! node v5.9.2-pre
> npm ERR! npm  v3.8.6
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
>
> npm ERR! tofino@0.1.0 postinstall: `electron-rebuild`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the tofino@0.1.0 postinstall script 'electron-rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm
> installed.
> npm ERR! If you do, this is most likely a problem with the tofino package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     electron-rebuild
> npm ERR! You can get information on how to open an issue for this project
> with:
> npm ERR!     npm bugs tofino
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls tofino
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/fabrizio/Scrivania/npm-debug.log
>


With webpack:

> root@debian:/home/fabrizio/Scrivania# npm install webpack -g
> /usr/local/bin/webpack ->
> /usr/local/lib/node_modules/webpack/bin/webpack.js
> /usr/local/lib
> └── webpack@1.12.15
>
> npm WARN optional Skipping failed optional dependency
> /webpack/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture:
> fsevents@1.0.11
> npm WARN You are using a pre-release version of node and things may not
> work as expected
> root@debian:/home/fabrizio/Scrivania#
>


2016-04-12 20:22 GMT+02:00 Lin Clark <notifications@github.com>:

**Comment by fabrixx** [comment] 2016-04-12 20:29
Now i'm trying with 5.8 stable instead of 5.9...

2016-04-12 22:19 GMT+02:00 fabrixx <fabrixx2@gmail.com>:

**Comment by fabrixx** [comment] 2016-04-12 21:56
This my situation after fixing node & npm:

> root@debian:/home/fabrizio/Scrivania# npm install tofino
> 
> > tofino@0.1.0 postinstall /home/fabrizio/Scrivania/node_modules/tofino
> > electron-rebuild
> 
> sh: 1: electron-rebuild: not found
> /home/fabrizio/Scrivania
> └── webpack@2.1.0-beta.5 
> 
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
> npm WARN enoent ENOENT: no such file or directory, open '/home/fabrizio/Scrivania/package.json'
> npm WARN Scrivania No description
> npm WARN Scrivania No repository field.
> npm WARN Scrivania No README data
> npm WARN Scrivania No license field.
> npm ERR! Linux 4.4.0-1-amd64
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "tofino"
> npm ERR! node v5.8.0
> npm ERR! npm  v3.7.3
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> 
> npm ERR! tofino@0.1.0 postinstall: `electron-rebuild`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the tofino@0.1.0 postinstall script 'electron-rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the tofino package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     electron-rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs tofino
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls tofino
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/fabrizio/Scrivania/npm-debug.log
> root@debian:/home/fabrizio/Scrivania# 

This is my npm-debug.log:
https://goo.gl/UrcTnf

**Comment by ddomgn** [comment] 2016-04-13 04:12
The problem is that the Node.js binary in Debian is /usr/bin/nodejs, not /usr/bin/node. Authors should fix build scripts. Read /usr/share/doc/nodejs/README.Debian for more details.

**Comment by fabrixx** [comment] 2016-04-13 18:12
Il 13 apr 2016 6:13 AM, "ddomgn" <notifications@github.com> ha scritto:

> The problem is that the Node.js binary in Debian is /usr/bin/nodejs, not
> /usr/bin/node. Authors should fix build scripts. Read
> /usr/share/doc/nodejs/README.Debian for more details.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/tofino/issues/91#issuecomment-209218491>
>

I not use Debian packeged version, ive builded all from sources.
Ive not usr/bin/nodejs file but

/usr/local/lib/node_modules
folders ---------->npm/tofino(symlink tolibrary)/webpack

/usr/local/bin:

---------->  webpack npm   symlynk to module folder
 ------------> node binary file

Than you for your patience..

**Comment by jsantell** [comment] 2016-04-15 03:43
Have you tried aliasing node as @ddomgn mentioned, wherever your node binary is?

I don't think this is an issue with this project

**Comment by jsantell** [comment] 2016-05-10 21:01
I don't believe this is an issue with this project. Closing for now, reopen if I'm wrong.

**Closed by jsantell** 2016-05-10 21:01 UTC
Labels: bug
