### ISSUE TITLE
When typing in location bar upon loading a new tab, gets overwritten by tofino://history

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1006] opened 2016-08-25 16:41 UTC
When opening a new tab (cmd+T) I begin typing the URL immediately and about a second later, `tofino://history` overwrites what I'm writing. We shouldn't inject that if the user already entered something. May be fixed by australification.

This is driving me nuts.

**Comment by bgrins** [comment] 2016-08-25 22:49
This is a dupe of #593

**Closed by bgrins** 2016-08-25 22:49 UTC
Labels: bug, frontend
