### ISSUE TITLE
fetch-mock spam

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#785] opened 2016-07-06 20:27 UTC
This gets dumped out when running tests. Should set `greed` to whatever makes sense.

```
/* * * * * * * * * * * * * * * * * * * * * * * */
Pro tip for fetch-mock:
By default any unmatched calls go straight through to `fetch`. Set `fetchMock.greed = 'bad'` to make them all error, or `fetchMock.greed = 'good'` to return `200` responses
/* * * * * * * * * * * * * * * * * * * * * * * */
```

**Comment by Mossop** [comment] 2016-07-06 21:32
It's worse than that. It seems to be outputting a random "tip" on every test run.

**Comment by Mossop** [comment] 2016-07-06 21:33
Looks like this was caused by https://github.com/wheresrhys/fetch-mock/pull/107

**Comment by Mossop** [comment] 2016-07-11 20:05
@jsantell Want to just downgrade us to 4.5.4, looks like the only difference between that and the current release is the tips.

**Comment by pdehaan** [comment] 2016-07-11 20:12
FWIW (not much), I filed a PR to disable the protips in CI environments; https://github.com/wheresrhys/fetch-mock/pull/109

**Comment by victorporof** [comment] 2016-07-20 05:20
This seems to be gone now, closing.

**Closed by victorporof** 2016-07-20 05:20 UTC
Labels: tests
