### ISSUE TITLE
History page background looks weird with no background colour

### ISSUE THREAD

**Issue by Mossop** [mozilla/tofino#1131] opened 2016-09-14 19:27 UTC
Running a local development build shows the blueprint background on the history start page but on packaged builds it is just a white background.

**Comment by jsantell** [comment] 2016-09-14 19:38
I think it's intentional to just show white background, as it's not using the blueprint theme at all anymore.

**Comment by Mossop** [comment] 2016-09-14 19:39
Then we shouldn't be showing it when running from a development tree either. it looks pretty weird without it though.

**Comment by Mossop** [comment] 2016-09-14 20:13
I guess I should have clobbered, it is indeed white locally too. I think it still needs something though.

**Comment by victorporof** [comment] 2016-09-15 05:51
Dupe of https://github.com/mozilla/tofino/issues/722

**Closed by victorporof** 2016-09-15 05:51 UTC

**Comment by victorporof** [comment] 2016-09-20 07:12
Didn't end up fixing things in #722, filed https://github.com/mozilla/tofino/issues/1170
