### ISSUE TITLE
It's easy to lose the service connection

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#640] opened 2016-06-07 21:46 UTC
I keep running into this, and could be from having an error in tests, or exiting via CLI, or who knows, but can very easily run into a scenario where my homepage (tofino://history) is just an error:

```
Error: This socket is closed
   at Socket._writeGeneric (net.js:672:19)
   at Socket._write (net.js:724:8)
   at doWrite (_stream_writable.js:307:12)
   at writeOrBuffer (_stream_writable.js:293:5)
   at Socket.Writable.write (_stream_writable.js:220:11)
   at Socket.write (net.js:650:40)
   at Console.warn (console.js:51:16)
   at /Users/jsantell/Dev/tofino/dist/tofino-darwin-x64/tofino.app/Contents/Resources/app/lib/services/common.js:85:19
   at Layer.handle_error (/Users/jsantell/Dev/tofino/dist/tofino-darwin-x64/tofino.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/Users/jsantell/Dev/tofino/dist/tofino-darwin-x64/tofino.app/Contents/Resources/app/node_modules/express/lib/router/index.js:310:13)
   at /Users/jsantell/Dev/tofino/dist/tofino-darwin-x64/tofino.app/Contents/Resources/app/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/jsantell/Dev/tofino/dist/tofino-darwin-x64/tofino.app/Contents/Resources/app/node_modules/express/lib/router/index.js:330:12)
   at Immediate.next (/Users/jsantell/Dev/tofino/dist/tofino-darwin-x64/tofino.app/Contents/Resources/app/node_modules/express/lib/router/index.js:271:10)
   at Immediate.<anonymous> (/Users/jsantell/Dev/tofino/dist/tofino-darwin-x64/tofino.app/Contents/Resources/app/node_modules/express/lib/router/index.js:618:15)
   at Immediate.immediate._onImmediate (timers.js:585:18)
   at tryOnImmediate (timers.js:543:15)
```

I don't think this is a unique thing for anyone developing on Tofino, and the solution is just to start killing node processes, which isn't a nice one either.

**Comment by victorporof** [comment] 2016-06-08 05:50
The service servers should always kill themselves now while doing development builds, and in tests too. The only place they are still kept alive is in packaged builds.

I don't remember the entire rationale behind why we'd want to keep services alive ever after their parent process is killed, but when I landed the PR that made these services lifetimes configurable, I kept this behavior for non-test production builds only to avoid some kind of regression for demos that we might want to make.

I do remember talking to @mossop about this, and the conclusions being:
* sometimes we might want to let the services servers running after a tofino opens them, but closes itself
* we probably never want this in development, to allow quick iteration and reloading new code when app starts
* users don't care about what happens behind the scenes, so we can keep the services alive for production
* tests don't need this

I'm not sure about the first bullet point in this list.

I'm still very much not in favor of having these servers running on the user's machine in the first place, since we're losing all the advantages of having them. It's important for development sure, but I see no reason for tofino itself starting them. That's why we now have a 'npm run serve' command, which does no magic whatsoever about server lifetimes: you ctr+c that, you kill everything, and stdout is piped.

I suggest we use 'npm run serve' exclusively.

**Closed** 2016-06-08 17:11 UTC
Labels: bug
