### ISSUE TITLE
Many gifs/videos on imgur show up as black squares

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1192] opened 2016-09-20 09:34 UTC
Probably similar to https://github.com/mozilla/tofino/issues/1050

Go to http://imgur.com/topic/Aww and browser for a while. Too much potential cat, too little viewable cat.

**Comment by jsantell** [comment] 2016-11-02 16:34
Dupe of #1050

**Closed by jsantell** 2016-11-02 16:34 UTC
Labels: backend:web-platform, bug, P5
