### ISSUE TITLE
Consider limiting use of `assert` to tests

### ISSUE THREAD

**Issue by linclark** [mozilla/tofino#550] opened 2016-05-26 15:28 UTC
I've usually only seen `assert` used in tests. Here's what it says in the project description:

> This module is used for writing unit tests for your applications, you can access it with require('assert').

We've been using it in reducers and elsewhere to validate arguments. Unless I misunderstand, these checks also run in production. This is exactly the kind of thing that React does in development, and the cost of doing these checks is why the production build of React is considerably faster than the development build.

My thinking is that we should limit the use of assert to tests. Anyone disagree?

**Comment by ncalexan** [comment] 2016-05-26 16:25
I want to fail when pre-conditions are not met, especially in production.  Hopefully we fail loudly.

I don't care if that's `assert` or `if` statements.

**Comment by jsantell** [comment] 2016-05-26 22:28
I've definitely found errors with these assertions -- although I've seen the overhead caused by React's dev mode prop type checking.

Isn't React's proptypes more involved than a single equality check, leading to the overhead? I'd be shocked if the asserts are adding that much overhead here, the assertion module [is just a conditional](https://github.com/nodejs/node/blob/841c7025a99719aad0c621dc4f57bfeefd789b5d/lib/assert.js#L109-L111), and seems like over optimizing, considering these have uncovered bugs.

I'd feel differently if we had TypeScript/Flow-that-worked-on-all-platforms, but assertions seem like a light-weight approach for the time being

**Comment by victorporof** [comment] 2016-05-26 22:39
Can't we just remove those asserts in production builds?

**Comment by victorporof** [comment] 2016-05-26 22:40
(through some custom babel rules, that either we or someone else possibly already wrote)

**Comment by linclark** [comment] 2016-05-26 22:53
I agree that for the time being, this isn't a big problem. I worry about it developing as a pattern as the project grows. But we don't have to address it immediately... not until we have something that provides the coverage we want.

@jsantell, if we used TypeScript (and didn't 👎), it sounds like you would be ok with us removing these? I could probably dedicate some cycles on the plane/train over the next couple of weeks to trying out TypeScript.

**Comment by ncalexan** [comment] 2016-05-26 23:11
@linclark I tried TS.  I would be thrilled if the FE devs started using it.  The UA service devs would definitely use it.  I found it tricky to get working with node-sqlite, although I think not impossible.  I ground out on the rocks of Node v6 and `async/await` in TS, which required Babel to happen after TS in our build files, which wasn't easy to arrange.  The fundamental issue I had there was that our build is single-file oriented but TS is fundamentally global.  I think we could `tsc` the project before running our Babeling.  Good luck!

Related but independent, I would like someone with more experience to think about using a mature build system / task launcher like gulp or grunt, because our build scripts are rigid and hard to generalize.

**Comment by jsantell** [comment] 2016-05-27 00:13
There are down sides to TS (like @ncalexan said, we'd have to compile everything on every change rather than file by file), but to get type assertions is well worth it IMO. That makes assertions much less valuable.

However, profiling the browser UI, `assert` isn't even picked up*. I think there are scenarios where removing assertions for a large performance increase (like React), but I don't think losing the benefits of assertions is worth this non-noticible performance gain.

* The node libs show up in the sources, but possibly might not show up in the profilers, but still, a conditional is orders of magnitude less than React rendering after a reducer

**Comment by linclark** [comment] 2016-05-27 00:29
Another reason I'd like to move away from `assert`, which I didn't make as explicit in the issue summary, is that I don't see other projects using assert this way. I may just never come across them, so please let me know if that's the case. But if other projects do not use it this way, I'd prefer not to. I have two reasons:

1. I think that it could make things more confusing to new contributors. We're using the package in a way that contradicts what the package's expressed purpose is. If I were a new contributor it would be a headscratcher for me.
2. I personally find it harder to see the logic in a function when there are lots of `assert` statements.

If others on the team feel strongly that we should use `assert` this way, I won't push to remove it. But I'd prefer it if we could find other solutions that give us the same benefits and aren't overly cumbersome.

**Comment by rnewman** [comment] 2016-05-27 01:26
I'm strongly in favor of defining preconditions etc. in code. I find them second only to a good type system for finding bugs.

A cursory skim of npm shows a bunch of libraries like [precond](https://www.npmjs.com/package/precond) and [preconditions](https://www.npmjs.com/package/preconditions) that serve exactly this purpose, but without using `assert`. Can we switch to one of those?

**Comment by linclark** [comment] 2016-05-27 01:36
Those two look like they haven't gotten much traction, but here's one that has gotten more traction: [babel-plugin-contracts](https://github.com/codemix/babel-plugin-contracts). Still not a huge fan of this because it would be a headscratcher for new contributors, but it's nice that you can configure it to strip out contracts in production.

**Comment by rnewman** [comment] 2016-05-27 01:51
I didn't suggest any of the contracts libraries because they don't seem to match the uses I found in our tree — we don't always have everything we want to check at the start of a function (e.g., in a dispatching `switch`, or after some lookup).

**Comment by linclark** [comment] 2016-05-27 02:07
That library also supports assertions and other things.

**Comment by rnewman** [comment] 2016-05-27 03:01
Oh, you're right! That's what I get for not reading closely enough. Thumbs up from me, then.

**Comment by jsantell** [comment] 2016-05-27 06:47
I'm just as happy with `if (typeof x !== 'number') throw new Error('x must be a number')` as I am with assertions, if it's a matter of using the `assert` module w/r/t new contributors. And I agree that they can be distracting from the main logic of the code, although having them all at the top of a function mitigates that for me. TypeScript would fix these!

**Comment by bgrins** [comment] 2016-06-09 19:38
Another solution is https://github.com/gcanti/tcomb.  Looks like it has some integrations with immutable and react proptypes as well

**Comment by victorporof** [comment] 2016-08-26 06:51
Closing this for now. Feel free to reopen.

**Closed by victorporof** 2016-08-26 06:51 UTC
Labels: backend, frontend, tests
