### ISSUE TITLE
Don't record some popup windows as primary history

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#743] opened 2016-06-26 14:29 UTC
I visited a page and clicked the "Share on Twitter" link.  Normally a tiny popup would launch but Tofino opens it in a new tab -- no big deal.  When I view the history list, however, the URL and page show up.

Is there a way we can identify URLs which we don't want to display as history?  Maybe URLs in named, sized windows?  Just a thought; feel free to simply close.

**Comment by jsantell** [comment] 2016-07-05 21:22
This should probably be handled on the UA service, filtering out (via configuration?) pages opened via popup style.

**Comment by rnewman** [comment] 2016-08-29 17:38
See also #663.

**Comment by jsantell** [comment] 2016-11-01 23:06
This is now a dupe of #663

**Closed by jsantell** 2016-11-01 23:06 UTC
Labels: frontend, P2
