### ISSUE TITLE
Use 7z for packaging

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/tofino#89] opened 2016-04-12 17:31 UTC
It provides nearly 50% compression ratio improvement due to solid archive.

I checked some similar formats (like tar.gz/bz2/xz), but they seem weaker than 7z. If this brings a compatibility issue, I hope it can serve as an alternative option or provided according to the platform.

**Comment by victorporof** [comment] 2016-04-12 17:59
Dupe of https://github.com/mozilla/tofino/issues/80

**Closed by victorporof** 2016-04-12 17:59 UTC
