### ISSUE TITLE
Filtering in the history page stopped working after updating UAS to 0.0.3

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1442] opened 2016-10-18 04:43 UTC

**Comment by victorporof** [comment] 2016-10-18 04:43
@ncalexan ping

**Comment by rnewman** [comment] 2016-10-18 05:17
I haven't looked at the root cause, but coincidentally I'm about to rework this in https://github.com/mozilla/datomish-user-agent-service/pull/22.

**Comment by jsantell** [comment] 2016-10-21 22:34
Fixed by incrementing datomish-user-agent-service to 0.0.4 via 6e190dca04b34439ea2b4e7aa992861efbd7a78c

**Closed by jsantell** 2016-10-21 22:34 UTC
Labels: backend:user-agent-service, bug, P1
